# Generated by Django 4.2.2 on 2023-06-25 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='budjet',
            new_name='budget',
        ),
    ]
