# Generated by Django 4.2.2 on 2023-06-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0005_movie_test_alter_movie_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.IntegerField(blank=True),
        ),
    ]
