# Generated by Django 4.2.2 on 2023-06-25 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0007_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='currency',
            field=models.CharField(choices=[('E', 'euro'), ('D', 'dollar'), ('R', 'ruble')], default='R', max_length=1),
        ),
    ]
